# Generated by Django 5.1.7 on 2025-04-06 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_tasktemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='day_of_week',
            field=models.CharField(blank=True, choices=[('Pzt', 'Pazartesi'), ('Sal', 'Salı'), ('Çar', 'Çarşamba'), ('Per', 'Perşembe'), ('Cum', 'Cuma'), ('Cmt', 'Cumartesi'), ('Paz', 'Pazar')], max_length=3, null=True),
        ),
    ]
