# Generated by Django 5.1.7 on 2025-04-27 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rewardhistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rewardhistory',
            old_name='date_redeemed',
            new_name='redeemed_at',
        ),
    ]
