# Generated by Django 5.1.7 on 2025-05-27 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_goal_end_date_goal_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_login_bonus',
            field=models.DateField(blank=True, null=True),
        ),
    ]
