# Generated by Django 5.1.7 on 2025-06-01 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_dailybonushistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='daily_bonus_claimed',
            field=models.DateField(blank=True, null=True),
        ),
    ]
