# Generated by Django 5.1.7 on 2025-06-07 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_challengeparticipation'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='is_shared',
            field=models.BooleanField(default=False),
        ),
    ]
