# Generated by Django 5.1.7 on 2025-06-10 19:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_goal_is_shared'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rewardhistory',
            unique_together={('user', 'reward')},
        ),
    ]
