# Generated by Django 5.1.7 on 2025-06-11 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_rewardhistory_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewardhistory',
            name='coupon_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
