# Generated by Django 5.1.4 on 2025-06-02 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Challenge',
        ),
    ]
